language: node_js
node_js:
  - "10.0"
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
script:
  
  # - npm test  
  - ng test --watch=false --progress=false --browsers=ChromeHeadlessCI
  - ng build
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: "1/DjAaKdpehxQbxlUH5XgUg_IimOL1CeJyF8jr5NWRrrs"